[programs.localnet]
bribe-vault = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/zano/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
